name: Gitleaks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gitleaks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.6
        with:
          # Remove the 'config' input if it was included previously
          args: detect --redact -v --exit-code=2 --report-format=sarif --report-path=results.sarif --log-level=debug --log-opts=-1
          
      - name: Upload Gitleaks results
        uses: actions/upload-artifact@v3
        with:
          name: gitleaks-results
          path: results.sarif
