name: Gitleaks

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  gitleaks:
    name: Run Gitleaks
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.6

      - name: Run Gitleaks
        uses: gitleaks/gitleaks-action@v2.3.6
        with:
          config: '.github/workflows/.gitleaks.toml'
